name: MadeWML
channels: 
  - conda-forge
  - pytorch
  - pip
dependencies:
  - python
  - jupyter
  - matplotlib
  - nltk
  - pandas
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - six
  - tqdm
  - urllib3
  - opencv
  - pip:
    - gensim
    - sklearn
    - torch
    - numpy
