name: MadeWML
channels: 
  - conda-forge
  - pytorch
dependencies:
  - python
  - gensim
  - jupyter
  - matplotlib
  - nltk
  - numpy
  - pandas
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - six
  - sklearn
  - torch
  - tqdm
  - urllib3
  - opencv
