name: MadeWML
channels: 
  - conda-forge
  - pytorch
  - pip
dependencies:
  - python=3.10.12
  - jupyter
  - matplotlib
  - nltk
  - pandas
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - six
  - tqdm
  - urllib3
  - opencv
  - gensim
  - pytorch
  - numpy
  - pip
  - pip:
       - sklearn
       - torch